config/routes.rb
Rails.application.routes.draw do
  resources :places do
    resources :comments
  end
  

  root 'places#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :place
end

app/models/place.rb
class Place < ActiveRecord::Base
	validates :name, presence: true
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
	@place = Place.find(params[:place_id])
	@comment = @place.comments.create(comment_params)
	redirect_to place_path(@place)
end

def destroy
    @place = Place.find(params[:place_id])
    @comment = @place.comments.find(params[:id])
    @comment.destroy
    redirect_to place_path(@place)
end
 
	private
	
	def comment_params
    	params.require(:comment).permit(:commenter, :body)
    end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
  	@places = Place.all.order(:name)
  end

  def show
  	@place = Place.find(params[:id])
  end

  def create
  	@place = Place.new(place_params)

  	if @place.save
	  	redirect_to @places
	else
		render :new
	end
  end
  
  def new
  	@place = Place.new
  end

  def edit
  	@place = Place.find(params[:id])
  end
  
  def update
  	@place = Place.find(params[:id])

  	if @place.update(place_params)
	  	redirect_to @places
	 else
	 	render :edit
	 end
  end
  
  def destroy
  	@place = Place.find(params[:id])

  	@place.destroy
	redirect_to places_path
  end

  private

  def place_params
  	params.require(:place).permit(:name, :description, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/comments/_comment.html.erb
<% @place.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
	
	<p>
	<%= link_to 'Delete Comment', [comment.place, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
	</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@place, @place.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LekkerPlekke</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/_form.html.erb
<% if @place.errors.any? %>
  <h2>
    <%= pluralize(@place.errors.count, "error") %>
    prohibited this place from being saved
  </h2>
  
  <ul>
    <% @place.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @place do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/places/edit.html.erb
<h1>Improve Plekke</h1>

<%= render 'form' %>
 
<p>
	<%= link_to 'Cancel Edit', place_path %>
</p>

<p>
	<%= link_to 'Back to All Plekkes', places_path %>
</p>

app/views/places/index.html.erb
<h1>Notable Plekkes in Cape Town</h1>
<% @places.each do |place| %>
	<strong><h3>
		<%= link_to place.name, place_path(place) %>
	</h3></strong>
	<p>
	<%= link_to 'Edit Plekke', edit_place_path(place) %>
	<%= link_to 'Delete Plekke', places_path(place),
				method: :delete,
				data: {confirm: 'Are you sure?'} %>
	<br><br><br></p>
<% end %>


<p><br><br>
	<%= link_to 'New Plekke, Bru', new_place_path %>
</p>

app/views/places/new.html.erb
<h1>Add a Notable Plekke from Cape Town</h1>

<%= render 'form' %>

<p><%= link_to 'Back', places_path %></p>

app/views/places/show.html.erb
<h1>Lekker Plekke</h1>

<h3><%= "#{@place.name}: "%></h3>
<p><%= @place.description %></p>

<h2>Comments</h2>
<%= render @place.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<p><br>
	<%= link_to 'Edit Plekke', edit_place_path %>
	<%= link_to 'Delete Plekke', places_path,
				method: :delete,
				data: {confirm: 'Are you sure?'} %>
</p>

<p>
	<%= link_to 'All Plekkes', places_path %>
</p>